### Successful register
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "kent@remix.com",
  "username": "kentcdodds",
  "password": "kentiscool"
}

### Failed register - email is taken
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "mjackson@gmail.com",
  "username": "ryanflorence",
  "password": "12345678"
}

### Successful login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "mzelinka17@gmail.com",
  "password": "123456789"
}

### Successful password update
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "mzelinka17@gmail.com",
  "password": "12345678"
}

