### Create user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "marek@remix.com",
  "username": "marekzelinka",
  "password": "marekiscool"
}

### Login with password
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "marek@remix.com",
  "password": "marekiscool"
}
